# -*- coding: utf-8 -*-
"""teste.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mDJ72DF77cVdjRwxe1FT0htQwUvWcBqj
"""

#!pip install streamlit

import streamlit as st
from pandas import read_excel, ExcelWriter

st.title("Minha primeira aplicação! :sunglasses:")